### ISSUE TITLE
Memory

### ISSUE THREAD

**Issue by jaikishantulswani** [trickest/mkpath#5]
@mhmdiaa Consuming 80% of ram while testing with list of 1000 words `mkpath -d example.com -l 2 -w 1000.txt`

**Comment by mhmdiaa** [comment]
Resolved in #6.

Thank you @jaikishantulswani!

**Comment by jaikishantulswani** [comment]
@mhmdiaa creating a hidden `.txt` file and not deleting even after completion of the process.

**Comment by mhmdiaa** [comment]
Hey @jaikishantulswani,

This is the output file. By default, mkpath will try to add a `.txt` extension to the output file name, so since you didn't specify an output file name, the name defaulted to just `.txt`.

To work around this, you can specify the output file with the `-o` parameter (instead of piping/redirecting the tool's output), and then only the name you specified will be used.
```
mkpath -d example.com -w wordlist.txt -o output.txt
```

We're definitely going to consider changing this behavior. Thanks!
